const solution = require('./06')
const primer = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`

test('Day 6', () => {
    expect(solution(primer)).toEqual({ part1: 41, part2: 6 })
})
