const solution = require('./11')
const primer = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`

test('Day 11', () => {
    expect(solution(primer)).toEqual({ part1: 367, part2: 0 })
})